version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abbrevio
    networks:
      - abbrevio-net

  abbrevio-rest:
    container_name: abbrevio-rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - abbrevio-net
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  abbrevio-net:
    driver: bridge
